телефонна книга додати меню
soosanin2/hamster_bot_git pull request #1
Opened 2023-05-26 12:54 UTC by soosanin2

2023-05-28 16:33 UTC, klymenok requested changes
Розділіть логіку вашої програми на декілька файлів, не пишіть все в одному, так як це важко сприймати

2023-05-28 16:33 UTC, klymenok commented on main.py
> +API = 'a455439cb8ea542bbe57143066b6990a' # ключ погоди
Ключ має бути в .env

2023-05-28 16:33 UTC, klymenok commented on main.py
> +# Функція для створення бази даних для нового користувача
Бажано не тримати все в одному файлі. Ви можете винести функції для роботи з базою даних в окремий файл

2023-05-31 14:43 UTC, soosanin2 commented on main.py
> +API = 'a455439cb8ea542bbe57143066b6990a' # ключ погоди
ключ переніс

2023-05-31 14:44 UTC, soosanin2 commented on main.py
> +# Функція для створення бази даних для нового користувача
Трішки розгрузив код

2023-06-06 13:55 UTC, soosanin2 commented on main.py
> +# Функція для створення бази даних для нового користувача
При спробі винести функції що стосуються бази даних, зіштовхнувся з циклічним імпортом. Треба буде змінити структуру проєкту, щоб не стикатися з подібним.

2023-06-08 12:12 UTC, merged